### ISSUE TITLE
我觉得库名可以改一下？

### ISSUE THREAD

**Issue by r7z7** [sngrotesque/wizard_key#6]
wmkc，Wizard Magic Key Cyber，在语义上是错误的。

要不改成“The magic key of a hacker wizard. (mkhw)”或者“The wizard's universal key. (wuk)”？
我倾向于换成后者。WMKC这个名字太奇怪了。

**Comment by sngrotesque** [comment]
嘶，确实，改成后者吧，然后把库中的名称改一下。
